package main;

import com.formdev.flatlaf.FlatLaf;
import com.formdev.flatlaf.FlatLightLaf;
import com.formdev.flatlaf.fonts.roboto.FlatRobotoFont;
import com.formdev.flatlaf.themes.FlatMacLightLaf;
import java.awt.BorderLayout;
import java.awt.Color;
import javax.swing.JFrame;
import javax.swing.JLabel;
import view.TabDashboard;
import view.TabDataBarang;
import view.TabLaporanStatistik;
import view.TabManajemenSampah;
import view.TabTransaksi;
import java.awt.EventQueue;
import java.awt.Font;
import javax.swing.UIManager;
import loginregister.loginregister;
import component.UserSession;
import loginregister.Login;
import view.TabManajemenNasabah;

/**
 *
 * @author devan
 */
public class Dashboard extends javax.swing.JFrame {

    private JLabel lastClickedLabel = null;
    private UserSession user;

    public Dashboard(UserSession user) {
        this.user = user;
        initComponents();

        setExtendedState(JFrame.MAXIMIZED_BOTH);
        setSidebarButtonEffect(dashboard);
        setSidebarButtonEffect(manajemen_nasabah);
        setSidebarButtonEffect(manajemen_sampah);
        setSidebarButtonEffect(laporan_statistik);
        setSidebarButtonEffect(transaksi);
        setSidebarButtonEffect(data_barang);
        panelMain.setLayout(new BorderLayout());
        lb_user.setText(user.getNama());
        lb_level.setText(user.getLevel());
        changeTabColor(dashboard);
        panelMain.setOpaque(false);
        panelMain.removeAll();
        panelMain.add(new TabDashboard());
        panelMain.repaint();
        panelMain.revalidate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pn_sidebar = new javax.swing.JPanel();
        panelMoving = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        dashboard = new javax.swing.JLabel();
        manajemen_nasabah = new javax.swing.JLabel();
        manajemen_sampah = new javax.swing.JLabel();
        laporan_statistik = new javax.swing.JLabel();
        transaksi = new javax.swing.JLabel();
        data_barang = new javax.swing.JLabel();
        panelMain = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        panelCredential = new javax.swing.JPanel();
        lb_level = new javax.swing.JLabel();
        lb_user = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pn_sidebar.setBackground(new java.awt.Color(255, 254, 84));
        pn_sidebar.setPreferredSize(new java.awt.Dimension(240, 1024));

        panelMoving.setOpaque(false);

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Admin Panel");

        javax.swing.GroupLayout panelMovingLayout = new javax.swing.GroupLayout(panelMoving);
        panelMoving.setLayout(panelMovingLayout);
        panelMovingLayout.setHorizontalGroup(
            panelMovingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelMovingLayout.setVerticalGroup(
            panelMovingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMovingLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel15)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        dashboard.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        dashboard.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        dashboard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icon_dashboard.png"))); // NOI18N
        dashboard.setText("Dashboard");
        dashboard.setPreferredSize(new java.awt.Dimension(240, 48));
        dashboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dashboardMouseClicked(evt);
            }
        });

        manajemen_nasabah.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        manajemen_nasabah.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        manajemen_nasabah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icon_manajemen_nasabah.png"))); // NOI18N
        manajemen_nasabah.setText("Manajemen Nasabah");
        manajemen_nasabah.setPreferredSize(new java.awt.Dimension(240, 48));
        manajemen_nasabah.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                manajemen_nasabahMouseClicked(evt);
            }
        });

        manajemen_sampah.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        manajemen_sampah.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        manajemen_sampah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icon_manajemen_sampah.png"))); // NOI18N
        manajemen_sampah.setText("Manajemen Sampah");
        manajemen_sampah.setPreferredSize(new java.awt.Dimension(240, 48));
        manajemen_sampah.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                manajemen_sampahMouseClicked(evt);
            }
        });

        laporan_statistik.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        laporan_statistik.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        laporan_statistik.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icon_laporan_statistik.png"))); // NOI18N
        laporan_statistik.setText("Laporan & Statistik");
        laporan_statistik.setPreferredSize(new java.awt.Dimension(240, 48));
        laporan_statistik.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                laporan_statistikMouseClicked(evt);
            }
        });

        transaksi.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        transaksi.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        transaksi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icon_transaksi.png"))); // NOI18N
        transaksi.setText("Transaksi");
        transaksi.setPreferredSize(new java.awt.Dimension(240, 48));
        transaksi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                transaksiMouseClicked(evt);
            }
        });

        data_barang.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        data_barang.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        data_barang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icon_data_barang.png"))); // NOI18N
        data_barang.setText("Data Barang");
        data_barang.setPreferredSize(new java.awt.Dimension(240, 48));
        data_barang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                data_barangMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pn_sidebarLayout = new javax.swing.GroupLayout(pn_sidebar);
        pn_sidebar.setLayout(pn_sidebarLayout);
        pn_sidebarLayout.setHorizontalGroup(
            pn_sidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelMoving, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(dashboard, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(manajemen_nasabah, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(manajemen_sampah, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(laporan_statistik, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(transaksi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(data_barang, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pn_sidebarLayout.setVerticalGroup(
            pn_sidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_sidebarLayout.createSequentialGroup()
                .addComponent(panelMoving, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(dashboard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(manajemen_nasabah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(manajemen_sampah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(laporan_statistik, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(transaksi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(data_barang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(545, Short.MAX_VALUE))
        );

        panelMain.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout panelMainLayout = new javax.swing.GroupLayout(panelMain);
        panelMain.setLayout(panelMainLayout);
        panelMainLayout.setHorizontalGroup(
            panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 952, Short.MAX_VALUE)
        );
        panelMainLayout.setVerticalGroup(
            panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 873, Short.MAX_VALUE)
        );

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        panelCredential.setBackground(new java.awt.Color(255, 255, 255));

        lb_level.setText("Admin");

        lb_user.setText("User");

        javax.swing.GroupLayout panelCredentialLayout = new javax.swing.GroupLayout(panelCredential);
        panelCredential.setLayout(panelCredentialLayout);
        panelCredentialLayout.setHorizontalGroup(
            panelCredentialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCredentialLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelCredentialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lb_user, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lb_level, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelCredentialLayout.setVerticalGroup(
            panelCredentialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCredentialLayout.createSequentialGroup()
                .addComponent(lb_user, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lb_level)
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 153));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 46, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(panelCredential, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(panelCredential, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(pn_sidebar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pn_sidebar, javax.swing.GroupLayout.DEFAULT_SIZE, 938, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3)
                        .addComponent(panelMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void data_barangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_data_barangMouseClicked
        changeTabColor(data_barang);
        panelMain.setOpaque(false);
        panelMain.removeAll();
        panelMain.add(new TabDataBarang());
        panelMain.repaint();
        panelMain.revalidate();
    }//GEN-LAST:event_data_barangMouseClicked

    private void transaksiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_transaksiMouseClicked
        changeTabColor(transaksi);
        panelMain.setOpaque(false);
        panelMain.removeAll();
        panelMain.add(new TabTransaksi());
        panelMain.repaint();
        panelMain.revalidate();
    }//GEN-LAST:event_transaksiMouseClicked

    private void laporan_statistikMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_laporan_statistikMouseClicked
        changeTabColor(laporan_statistik);
        panelMain.setOpaque(false);
        panelMain.removeAll();
        panelMain.add(new TabLaporanStatistik());
        panelMain.repaint();
        panelMain.revalidate();
    }//GEN-LAST:event_laporan_statistikMouseClicked

    private void manajemen_sampahMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_manajemen_sampahMouseClicked
        changeTabColor(manajemen_sampah);
        panelMain.setOpaque(false);
        panelMain.removeAll();
        panelMain.add(new TabManajemenSampah());
        panelMain.repaint();
        panelMain.revalidate();
    }//GEN-LAST:event_manajemen_sampahMouseClicked

    private void manajemen_nasabahMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_manajemen_nasabahMouseClicked
        changeTabColor(manajemen_nasabah);
        panelMain.setOpaque(false);
        panelMain.removeAll();
        panelMain.add(new TabManajemenNasabah(user));
        panelMain.repaint();
        panelMain.revalidate();
    }//GEN-LAST:event_manajemen_nasabahMouseClicked

    private void dashboardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dashboardMouseClicked
        changeTabColor(dashboard);
        panelMain.setOpaque(false);
        panelMain.removeAll();
        panelMain.add(new TabDashboard());
        panelMain.repaint();
        panelMain.revalidate();
    }//GEN-LAST:event_dashboardMouseClicked
    private void setSidebarButtonEffect(JLabel label) {
        Color defaultColor = new Color(255, 254, 84);
        Color hoverColor = new Color(255, 230, 100);
        Color clickColor = new Color(255, 200, 50);

        label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                // Jika tab sudah diklik, jangan ganti warna menjadi hover
                if (label != lastClickedLabel) {
                    label.setBackground(hoverColor);
                    label.setOpaque(true);
                    label.repaint();
                }
            }

            public void mouseExited(java.awt.event.MouseEvent evt) {
                // Kembalikan ke default jika tidak diklik
                if (label != lastClickedLabel) {
                    label.setBackground(defaultColor);
                    label.setOpaque(true);
                    label.repaint();
                }
            }

            public void mousePressed(java.awt.event.MouseEvent evt) {
                label.setBackground(clickColor);
                label.setOpaque(true);
                label.repaint();
            }

            public void mouseReleased(java.awt.event.MouseEvent evt) {
                // Jika tab sudah diklik, tetap pertahankan warna aktif
                if (label != lastClickedLabel) {
                    label.setBackground(hoverColor);
                    label.setOpaque(true);
                    label.repaint();
                }
            }
        });
    }

    private void changeTabColor(JLabel newLabel) {
        Color defaultColor = new Color(255, 254, 84);
        Color clickColor = new Color(255, 200, 50);

        // Kembalikan warna tab yang sebelumnya diklik ke default
        if (lastClickedLabel != null && lastClickedLabel != newLabel) {
            lastClickedLabel.setBackground(defaultColor);
            lastClickedLabel.setOpaque(true);
            lastClickedLabel.repaint();
        }

        // Ubah warna tab yang baru diklik
        newLabel.setBackground(clickColor);
        newLabel.setOpaque(true);
        newLabel.repaint();

        // Simpan tab yang terakhir diklik
        lastClickedLabel = newLabel;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        FlatRobotoFont.install();
        FlatLaf.registerCustomDefaultsSource("themes");
        FlatMacLightLaf.setup();
        UIManager.put("defaultFont", new Font(FlatRobotoFont.FAMILY, Font.PLAIN, 13));
        EventQueue.invokeLater(() -> new loginregister().setVisible(true));
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FlatLightLaf.setup();
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel dashboard;
    private javax.swing.JLabel data_barang;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel laporan_statistik;
    private javax.swing.JLabel lb_level;
    private javax.swing.JLabel lb_user;
    private javax.swing.JLabel manajemen_nasabah;
    private javax.swing.JLabel manajemen_sampah;
    private javax.swing.JPanel panelCredential;
    private javax.swing.JPanel panelMain;
    private javax.swing.JPanel panelMoving;
    private javax.swing.JPanel pn_sidebar;
    private javax.swing.JLabel transaksi;
    // End of variables declaration//GEN-END:variables
}
