/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import main.DBconnect;

/**
 *
 * @author devan
 */
public class TabDashboard extends javax.swing.JPanel {

    private final Connection conn;

    public TabDashboard() {
        conn = DBconnect.getConnection();
        initComponents();
        loadDashboardData();
        setTabelModel();
        loadLogData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelUtama = new component.DashboardPanel();
        ShadowAktivitas = new component.ShadowPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_log = new component.Table();
        ShadowCard = new component.ShadowPanel();
        CardTotalNasabah = new component.Card();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lb_totalNasabah = new javax.swing.JLabel();
        CardTotalSampah = new component.Card();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lb_totalSampah = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        CardSaldoTabungan = new component.Card();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        lb_totalTabungan = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();

        PanelUtama.setBackground(new java.awt.Color(255, 255, 255));

        tbl_log.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tbl_log);

        javax.swing.GroupLayout ShadowAktivitasLayout = new javax.swing.GroupLayout(ShadowAktivitas);
        ShadowAktivitas.setLayout(ShadowAktivitasLayout);
        ShadowAktivitasLayout.setHorizontalGroup(
            ShadowAktivitasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ShadowAktivitasLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 543, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        ShadowAktivitasLayout.setVerticalGroup(
            ShadowAktivitasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ShadowAktivitasLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 640, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(82, 82, 82))
        );

        ShadowCard.setPreferredSize(new java.awt.Dimension(1182, 126));

        CardTotalNasabah.setPreferredSize(new java.awt.Dimension(315, 99));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icon_total_nasabah.png"))); // NOI18N

        jLabel6.setForeground(new java.awt.Color(153, 153, 153));
        jLabel6.setText("Total nasabah");

        lb_totalNasabah.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lb_totalNasabah.setText("1.000");

        javax.swing.GroupLayout CardTotalNasabahLayout = new javax.swing.GroupLayout(CardTotalNasabah);
        CardTotalNasabah.setLayout(CardTotalNasabahLayout);
        CardTotalNasabahLayout.setHorizontalGroup(
            CardTotalNasabahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CardTotalNasabahLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(CardTotalNasabahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(lb_totalNasabah))
                .addContainerGap(171, Short.MAX_VALUE))
        );
        CardTotalNasabahLayout.setVerticalGroup(
            CardTotalNasabahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CardTotalNasabahLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(CardTotalNasabahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(CardTotalNasabahLayout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lb_totalNasabah))
                    .addComponent(jLabel5))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        CardTotalSampah.setPreferredSize(new java.awt.Dimension(315, 99));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icon_total_sampah.png"))); // NOI18N

        jLabel9.setForeground(new java.awt.Color(153, 153, 153));
        jLabel9.setText("Total sampah");

        lb_totalSampah.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lb_totalSampah.setText("1.000");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("KG");

        javax.swing.GroupLayout CardTotalSampahLayout = new javax.swing.GroupLayout(CardTotalSampah);
        CardTotalSampah.setLayout(CardTotalSampahLayout);
        CardTotalSampahLayout.setHorizontalGroup(
            CardTotalSampahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CardTotalSampahLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(CardTotalSampahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addGroup(CardTotalSampahLayout.createSequentialGroup()
                        .addComponent(lb_totalSampah)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1)))
                .addContainerGap(143, Short.MAX_VALUE))
        );
        CardTotalSampahLayout.setVerticalGroup(
            CardTotalSampahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CardTotalSampahLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(CardTotalSampahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(CardTotalSampahLayout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(CardTotalSampahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lb_totalSampah)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel8))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        CardSaldoTabungan.setPreferredSize(new java.awt.Dimension(315, 99));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icon_total_tabungan.png"))); // NOI18N

        jLabel12.setForeground(new java.awt.Color(153, 153, 153));
        jLabel12.setText("Saldo tabungan");

        lb_totalTabungan.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lb_totalTabungan.setText("Rp 1.000");

        javax.swing.GroupLayout CardSaldoTabunganLayout = new javax.swing.GroupLayout(CardSaldoTabungan);
        CardSaldoTabungan.setLayout(CardSaldoTabunganLayout);
        CardSaldoTabunganLayout.setHorizontalGroup(
            CardSaldoTabunganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CardSaldoTabunganLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(CardSaldoTabunganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(lb_totalTabungan))
                .addContainerGap(143, Short.MAX_VALUE))
        );
        CardSaldoTabunganLayout.setVerticalGroup(
            CardSaldoTabunganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CardSaldoTabunganLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(CardSaldoTabunganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(CardSaldoTabunganLayout.createSequentialGroup()
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lb_totalTabungan))
                    .addComponent(jLabel11))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout ShadowCardLayout = new javax.swing.GroupLayout(ShadowCard);
        ShadowCard.setLayout(ShadowCardLayout);
        ShadowCardLayout.setHorizontalGroup(
            ShadowCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ShadowCardLayout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(CardTotalNasabah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(CardTotalSampah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(CardSaldoTabungan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(94, Short.MAX_VALUE))
        );
        ShadowCardLayout.setVerticalGroup(
            ShadowCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ShadowCardLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(ShadowCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(CardSaldoTabungan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(CardTotalSampah, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(CardTotalNasabah, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel14.setText("Aktivitas terbaru");

        javax.swing.GroupLayout PanelUtamaLayout = new javax.swing.GroupLayout(PanelUtama);
        PanelUtama.setLayout(PanelUtamaLayout);
        PanelUtamaLayout.setHorizontalGroup(
            PanelUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelUtamaLayout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(PanelUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(ShadowAktivitas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(ShadowCard, javax.swing.GroupLayout.DEFAULT_SIZE, 1192, Short.MAX_VALUE)
        );
        PanelUtamaLayout.setVerticalGroup(
            PanelUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelUtamaLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(ShadowCard, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ShadowAktivitas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1192, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(PanelUtama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 967, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(PanelUtama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private component.Card CardSaldoTabungan;
    private component.Card CardTotalNasabah;
    private component.Card CardTotalSampah;
    private component.DashboardPanel PanelUtama;
    private component.ShadowPanel ShadowAktivitas;
    private component.ShadowPanel ShadowCard;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lb_totalNasabah;
    private javax.swing.JLabel lb_totalSampah;
    private javax.swing.JLabel lb_totalTabungan;
    private component.Table tbl_log;
    // End of variables declaration//GEN-END:variables
    private void setTabelModel() {
        DefaultTableModel model = (DefaultTableModel) tbl_log.getModel();
        model.addColumn("ID");
        model.addColumn("Admin");
        model.addColumn("Aktivitas");
        model.addColumn("Tanggal");
    }

    private void getData(DefaultTableModel model) {
        model.setRowCount(0);

        try {
            String sql = "SELECT * FROM log_aktivitas";
            try (PreparedStatement st = conn.prepareStatement(sql)) {
                ResultSet rs = st.executeQuery();

                while (rs.next()) {
                    String idLog = rs.getString("id");
                    String admin = rs.getString("admin");
                    String aktivitas = rs.getString("aktivitas");
                    String tanggal = rs.getString("tanggal");

                    Object[] rowData = {idLog, admin, aktivitas, tanggal};
                    model.addRow(rowData);

                }
            }
        } catch (SQLException e) {
            Logger.getLogger(TabManajemenNasabah.class.getName()).log(Level.SEVERE, null, e);
        }
    }

    private void loadLogData() {
        getData((DefaultTableModel) tbl_log.getModel());
    }

    public void loadDashboardData() {
        try {
            Connection conn = DBconnect.getConnection();
            Statement stmt = conn.createStatement();

            // Total Nasabah
            ResultSet rsNasabah = stmt.executeQuery("SELECT COUNT(*) FROM manajemen_nasabah");
            if (rsNasabah.next()) {
                int totalNasabah = rsNasabah.getInt(1);
                lb_totalNasabah.setText(String.valueOf(totalNasabah));
            }

            // Total Sampah
            ResultSet rsSampah = stmt.executeQuery("SELECT SUM(berat_sampah) FROM setor_sampah");
            if (rsSampah.next()) {
                double totalSampah = rsSampah.getDouble(1);
                lb_totalSampah.setText(String.valueOf(totalSampah));
            }

            // Saldo Tabungan = pemasukan - pengeluaran
            ResultSet rsPemasukan = stmt.executeQuery(
                    "SELECT SUM(db.harga * sub.jml) AS total_pemasukan "
                    + "FROM ("
                    + "   SELECT id_barang, COUNT(*) AS jml "
                    + "   FROM laporan_pemasukan "
                    + "   GROUP BY id_barang"
                    + ") AS sub "
                    + "JOIN data_barang db ON sub.id_barang = db.id_barang"
            );

            double pemasukan = rsPemasukan.next() ? rsPemasukan.getDouble("total_pemasukan") : 0;

            ResultSet rsPengeluaran = stmt.executeQuery(
                    "SELECT SUM(nominal) FROM manajemen_keuangan"
            );
            double pengeluaran = rsPengeluaran.next() ? rsPengeluaran.getDouble(1) : 0;

            double saldo = pemasukan - pengeluaran;
            lb_totalTabungan.setText("Rp " + String.format("%,.0f", saldo));

            conn.close();

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Gagal memuat data dashboard: " + e.getMessage());
        }
    }

    private void insertLog(String admin, String aktivitas) {
        try {
            String sql = "INSERT INTO log_aktivitas (admin, aktivitas) VALUES (?, ?)";
            try (PreparedStatement st = conn.prepareStatement(sql)) {
                st.setString(1, admin);
                st.setString(2, aktivitas);
                st.executeUpdate();
            }
        } catch (SQLException e) {
            Logger.getLogger(TabDashboard.class.getName()).log(Level.SEVERE, null, e);
        }
    }

}
