package view;

import component.Jbutton;
import java.awt.Color;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import main.DBconnect;

public class TabManajemenSampah extends javax.swing.JPanel {

    private final Connection conn = DBconnect.getConnection();
    private DefaultTableModel tblModel;
    private int selectedIdSampah = -1; // default -1 berarti belum ada yang dipilih

    public TabManajemenSampah() {
        initComponents();
        inisialisasiTabel();
        loadTabelSampah();
    }

    private void showPanel() {
        panelMain.removeAll();
        panelMain.add(new TabManajemenSampah());
        panelMain.repaint();
        panelMain.revalidate();
        loadTabelSampah();
    }

    private void inisialisasiTabel() {
        // Mengatur model tabel
        tblModel = new DefaultTableModel(new String[]{"ID Sampah", "Jenis Sampah", "Kategori Sampah", "Harga/Kg"}, 0);
        tblSampah.setModel(tblModel);
        // Sembunyikan kolom ID (kolom ke-0)
        tblSampah.getColumnModel().getColumn(0).setMinWidth(0);
        tblSampah.getColumnModel().getColumn(0).setMaxWidth(0);
        tblSampah.getColumnModel().getColumn(0).setWidth(0);

    }

    private void loadTabelSampah() {
        try (Statement stmt = conn.createStatement(); ResultSet rs = stmt.executeQuery("SELECT * FROM sampah")) {

            DefaultTableModel model = (DefaultTableModel) tblSampah.getModel();
            model.setRowCount(0); // Hapus data tabel

            while (rs.next()) {
                Object[] row = {
                    rs.getInt("id_sampah"),
                    rs.getString("jenis_sampah"),
                    rs.getString("kategori_sampah"),
                    rs.getDouble("harga_sampah"),
                };
                model.addRow(row);
            }

        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());
        }
    }

    private void clearPanelAdd() {
        txt_JenisAdd.setText("");
        txt_KategoriAdd.setText("");
        txt_HargaAdd.setText("");
    }

    private void clearPanelEdit() {
        txt_HargaEdit.setText("");
        txt_JenisEdit.setText("");
        txt_KategoriEdit.setText("");
    }

    private void setPanelEditFormData(int selectedRow) {
        txt_JenisEdit.setText(tblSampah.getValueAt(selectedRow, 1).toString());
        txt_KategoriEdit.setText(tblSampah.getValueAt(selectedRow, 2).toString());
        txt_HargaEdit.setText(tblSampah.getValueAt(selectedRow, 3).toString());

        selectedIdSampah = Integer.parseInt(tblSampah.getValueAt(selectedRow, 0).toString());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelMain = new javax.swing.JPanel();
        panelView = new javax.swing.JPanel();
        ShadowUtama = new component.ShadowPanel();
        shadowPanel1 = new component.ShadowPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txt_Nama = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cbxJenis = new javax.swing.JComboBox<>();
        cbxKategori = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        txt_Berat = new javax.swing.JTextField();
        btn_SetorSampah = new component.Jbutton();
        jLabel10 = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();
        txt_Kode = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        shadowPanel2 = new component.ShadowPanel();
        jLabel15 = new javax.swing.JLabel();
        btnRiwayatSetor = new component.Jbutton();
        shadowPanel3 = new component.ShadowPanel();
        jLabel16 = new javax.swing.JLabel();
        btnTambahHarga = new component.Jbutton();
        btnHapusHarga = new component.Jbutton();
        btnBatalHarga = new component.Jbutton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSampah = new component.Table();
        btnEditHarga = new component.Jbutton();
        panelAdd = new javax.swing.JPanel();
        ShadowUtama1 = new component.ShadowPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txt_KategoriAdd = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txt_HargaAdd = new javax.swing.JTextField();
        btnSimpanHarga = new component.Jbutton();
        btnKembaliT = new component.Jbutton();
        txt_JenisAdd = new javax.swing.JTextField();
        panelEdit = new javax.swing.JPanel();
        ShadowUtama3 = new component.ShadowPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        txt_KategoriEdit = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        txt_HargaEdit = new javax.swing.JTextField();
        btnSimpanEdit = new component.Jbutton();
        btnKembaliE = new component.Jbutton();
        txt_JenisEdit = new javax.swing.JTextField();
        panelRiwayat = new javax.swing.JPanel();
        ShadowUtama2 = new component.ShadowPanel();
        jLabel7 = new javax.swing.JLabel();
        btnKembaliR = new component.Jbutton();
        jScrollPane2 = new javax.swing.JScrollPane();
        table2 = new component.Table();
        ShadowSearch1 = new component.ShadowPanel();
        jLabel9 = new javax.swing.JLabel();
        btnFirstPage = new javax.swing.JButton();
        btnPrevious = new javax.swing.JButton();
        cbxPage = new javax.swing.JComboBox<>();
        btnNext = new javax.swing.JButton();
        btnLastPage = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(1200, 716));
        setLayout(new java.awt.CardLayout());

        panelMain.setLayout(new java.awt.CardLayout());

        panelView.setLayout(new java.awt.CardLayout());

        ShadowUtama.setBackground(new java.awt.Color(250, 250, 250));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        jLabel2.setText("Input Setoran Sampah ");

        jLabel1.setFont(new java.awt.Font("Mongolian Baiti", 0, 12)); // NOI18N
        jLabel1.setText("Kode Nasabah");

        txt_Nama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_NamaActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Mongolian Baiti", 0, 12)); // NOI18N
        jLabel3.setText("Jenis Sampah");

        jLabel4.setFont(new java.awt.Font("Mongolian Baiti", 0, 12)); // NOI18N
        jLabel4.setText("Kategori");

        cbxJenis.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cbxKategori.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel5.setFont(new java.awt.Font("Mongolian Baiti", 0, 12)); // NOI18N
        jLabel5.setText("Berat sampah");

        txt_Berat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_BeratActionPerformed(evt);
            }
        });

        btn_SetorSampah.setBackground(new java.awt.Color(255, 255, 51));
        btn_SetorSampah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icon_tambah.png"))); // NOI18N
        btn_SetorSampah.setText("Setor");
        btn_SetorSampah.setFillClick(new java.awt.Color(55, 130, 60));
        btn_SetorSampah.setFillOriginal(new java.awt.Color(76, 175, 80));
        btn_SetorSampah.setFillOver(new java.awt.Color(69, 160, 75));
        btn_SetorSampah.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_SetorSampah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SetorSampahActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("NSimSun", 0, 20)); // NOI18N
        jLabel10.setText("Rp.");

        lblTotal.setFont(new java.awt.Font("NSimSun", 0, 48)); // NOI18N
        lblTotal.setText("0");

        txt_Kode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_KodeActionPerformed(evt);
            }
        });
        txt_Kode.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_KodeKeyPressed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Mongolian Baiti", 0, 12)); // NOI18N
        jLabel17.setText("Nama Nasabah");

        jLabel20.setText("jLabel20");

        javax.swing.GroupLayout shadowPanel1Layout = new javax.swing.GroupLayout(shadowPanel1);
        shadowPanel1.setLayout(shadowPanel1Layout);
        shadowPanel1Layout.setHorizontalGroup(
            shadowPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(shadowPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(shadowPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3)
                    .addGroup(shadowPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel20)
                        .addGap(10, 10, 10))
                    .addComponent(jLabel5)
                    .addComponent(txt_Berat)
                    .addComponent(cbxKategori, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_SetorSampah, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, shadowPanel1Layout.createSequentialGroup()
                        .addGroup(shadowPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(shadowPanel1Layout.createSequentialGroup()
                                .addComponent(txt_Kode)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(shadowPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(119, 119, 119)))
                        .addGroup(shadowPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17)
                            .addComponent(txt_Nama, javax.swing.GroupLayout.PREFERRED_SIZE, 525, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel4)
                    .addComponent(cbxJenis, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
        );
        shadowPanel1Layout.setVerticalGroup(
            shadowPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(shadowPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(shadowPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(shadowPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(shadowPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_Nama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_Kode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(shadowPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, shadowPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(lblTotal)
                        .addGroup(shadowPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel10)
                            .addGap(51, 51, 51)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, shadowPanel1Layout.createSequentialGroup()
                        .addComponent(cbxJenis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbxKategori, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_Berat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_SetorSampah, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        jLabel15.setText("Riwayat Setoran");

        btnRiwayatSetor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icon_Riwayat.png"))); // NOI18N
        btnRiwayatSetor.setText("Lihat Riwayat");
        btnRiwayatSetor.setFillClick(new java.awt.Color(200, 125, 0));
        btnRiwayatSetor.setFillOriginal(new java.awt.Color(243, 156, 18));
        btnRiwayatSetor.setFillOver(new java.awt.Color(230, 145, 10));
        btnRiwayatSetor.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnRiwayatSetor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRiwayatSetorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout shadowPanel2Layout = new javax.swing.GroupLayout(shadowPanel2);
        shadowPanel2.setLayout(shadowPanel2Layout);
        shadowPanel2Layout.setHorizontalGroup(
            shadowPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(shadowPanel2Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(shadowPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnRiwayatSetor, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        shadowPanel2Layout.setVerticalGroup(
            shadowPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(shadowPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnRiwayatSetor, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        jLabel16.setText("Daftar Harga Sampah/KG");

        btnTambahHarga.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icon_tambah.png"))); // NOI18N
        btnTambahHarga.setText("Tambah");
        btnTambahHarga.setFillClick(new java.awt.Color(55, 130, 60));
        btnTambahHarga.setFillOriginal(new java.awt.Color(76, 175, 80));
        btnTambahHarga.setFillOver(new java.awt.Color(69, 160, 75));
        btnTambahHarga.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnTambahHarga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahHargaActionPerformed(evt);
            }
        });

        btnHapusHarga.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icon_hapus.png"))); // NOI18N
        btnHapusHarga.setText("Hapus");
        btnHapusHarga.setEnabled(false);
        btnHapusHarga.setFillClick(new java.awt.Color(190, 30, 20));
        btnHapusHarga.setFillOriginal(new java.awt.Color(231, 76, 60));
        btnHapusHarga.setFillOver(new java.awt.Color(210, 50, 40));
        btnHapusHarga.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnHapusHarga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusHargaActionPerformed(evt);
            }
        });

        btnBatalHarga.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icon_batal.png"))); // NOI18N
        btnBatalHarga.setText("Batal");
        btnBatalHarga.setFillClick(new java.awt.Color(200, 125, 0));
        btnBatalHarga.setFillOriginal(new java.awt.Color(243, 156, 18));
        btnBatalHarga.setFillOver(new java.awt.Color(230, 145, 10));
        btnBatalHarga.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnBatalHarga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatalHargaActionPerformed(evt);
            }
        });

        tblSampah.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Jenis Sampah", "Kategori Sampah", "Harga per Kg"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblSampah.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        tblSampah.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblSampahMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblSampah);
        if (tblSampah.getColumnModel().getColumnCount() > 0) {
            tblSampah.getColumnModel().getColumn(0).setResizable(false);
            tblSampah.getColumnModel().getColumn(1).setResizable(false);
            tblSampah.getColumnModel().getColumn(2).setResizable(false);
        }

        btnEditHarga.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icon_edit.png"))); // NOI18N
        btnEditHarga.setText("Edit");
        btnEditHarga.setEnabled(false);
        btnEditHarga.setFillClick(new java.awt.Color(51, 51, 255));
        btnEditHarga.setFillOriginal(new java.awt.Color(102, 204, 255));
        btnEditHarga.setFillOver(new java.awt.Color(102, 102, 255));
        btnEditHarga.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnEditHarga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditHargaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout shadowPanel3Layout = new javax.swing.GroupLayout(shadowPanel3);
        shadowPanel3.setLayout(shadowPanel3Layout);
        shadowPanel3Layout.setHorizontalGroup(
            shadowPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(shadowPanel3Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(shadowPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1159, Short.MAX_VALUE)
                    .addGroup(shadowPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnTambahHarga, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEditHarga, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnHapusHarga, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBatalHarga, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        shadowPanel3Layout.setVerticalGroup(
            shadowPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(shadowPanel3Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(shadowPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                    .addComponent(btnHapusHarga, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnBatalHarga, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEditHarga, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnTambahHarga, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(178, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout ShadowUtamaLayout = new javax.swing.GroupLayout(ShadowUtama);
        ShadowUtama.setLayout(ShadowUtamaLayout);
        ShadowUtamaLayout.setHorizontalGroup(
            ShadowUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(shadowPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(shadowPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(shadowPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        ShadowUtamaLayout.setVerticalGroup(
            ShadowUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ShadowUtamaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(shadowPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(shadowPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(shadowPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        panelView.add(ShadowUtama, "card2");

        panelMain.add(panelView, "card2");

        panelAdd.setLayout(new java.awt.CardLayout());

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        jLabel6.setText("Tambah Harga Sampah");

        jLabel11.setFont(new java.awt.Font("Mongolian Baiti", 0, 14)); // NOI18N
        jLabel11.setText("Jenis Sampah");

        jLabel12.setFont(new java.awt.Font("Mongolian Baiti", 0, 14)); // NOI18N
        jLabel12.setText("Kategori");

        txt_KategoriAdd.setPreferredSize(new java.awt.Dimension(20, 22));

        jLabel13.setFont(new java.awt.Font("Mongolian Baiti", 0, 14)); // NOI18N
        jLabel13.setText("Harga/Kg");

        txt_HargaAdd.setPreferredSize(new java.awt.Dimension(20, 22));

        btnSimpanHarga.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icon_simpan.png"))); // NOI18N
        btnSimpanHarga.setText("Simpan");
        btnSimpanHarga.setFillClick(new java.awt.Color(30, 100, 150));
        btnSimpanHarga.setFillOriginal(new java.awt.Color(41, 128, 185));
        btnSimpanHarga.setFillOver(new java.awt.Color(36, 116, 170));
        btnSimpanHarga.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSimpanHarga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanHargaActionPerformed(evt);
            }
        });

        btnKembaliT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icon_batal.png"))); // NOI18N
        btnKembaliT.setText("Kembali");
        btnKembaliT.setFillClick(new java.awt.Color(200, 125, 0));
        btnKembaliT.setFillOriginal(new java.awt.Color(243, 156, 18));
        btnKembaliT.setFillOver(new java.awt.Color(230, 145, 10));
        btnKembaliT.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnKembaliT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKembaliTActionPerformed(evt);
            }
        });

        txt_JenisAdd.setPreferredSize(new java.awt.Dimension(20, 22));

        javax.swing.GroupLayout ShadowUtama1Layout = new javax.swing.GroupLayout(ShadowUtama1);
        ShadowUtama1.setLayout(ShadowUtama1Layout);
        ShadowUtama1Layout.setHorizontalGroup(
            ShadowUtama1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ShadowUtama1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(ShadowUtama1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ShadowUtama1Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(ShadowUtama1Layout.createSequentialGroup()
                        .addGroup(ShadowUtama1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_KategoriAdd, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txt_HargaAdd, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(ShadowUtama1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 720, Short.MAX_VALUE)
                                .addComponent(btnSimpanHarga, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnKembaliT, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txt_JenisAdd, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 40, Short.MAX_VALUE))))
        );
        ShadowUtama1Layout.setVerticalGroup(
            ShadowUtama1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ShadowUtama1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(ShadowUtama1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ShadowUtama1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnSimpanHarga, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE))
                    .addComponent(btnKembaliT, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_JenisAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_KategoriAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_HargaAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(730, Short.MAX_VALUE))
        );

        panelAdd.add(ShadowUtama1, "card2");

        panelEdit.setLayout(new java.awt.CardLayout());

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        jLabel8.setText("Edit Harga Sampah");

        jLabel14.setFont(new java.awt.Font("Mongolian Baiti", 0, 14)); // NOI18N
        jLabel14.setText("Jenis Sampah");

        jLabel18.setFont(new java.awt.Font("Mongolian Baiti", 0, 14)); // NOI18N
        jLabel18.setText("Kategori");

        txt_KategoriEdit.setPreferredSize(new java.awt.Dimension(20, 22));

        jLabel19.setFont(new java.awt.Font("Mongolian Baiti", 0, 14)); // NOI18N
        jLabel19.setText("Harga/Kg");

        txt_HargaEdit.setPreferredSize(new java.awt.Dimension(20, 22));

        btnSimpanEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icon_simpan.png"))); // NOI18N
        btnSimpanEdit.setText("Simpan");
        btnSimpanEdit.setFillClick(new java.awt.Color(30, 100, 150));
        btnSimpanEdit.setFillOriginal(new java.awt.Color(41, 128, 185));
        btnSimpanEdit.setFillOver(new java.awt.Color(36, 116, 170));
        btnSimpanEdit.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSimpanEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanEditActionPerformed(evt);
            }
        });

        btnKembaliE.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icon_batal.png"))); // NOI18N
        btnKembaliE.setText("Kembali");
        btnKembaliE.setFillClick(new java.awt.Color(200, 125, 0));
        btnKembaliE.setFillOriginal(new java.awt.Color(243, 156, 18));
        btnKembaliE.setFillOver(new java.awt.Color(230, 145, 10));
        btnKembaliE.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnKembaliE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKembaliEActionPerformed(evt);
            }
        });

        txt_JenisEdit.setPreferredSize(new java.awt.Dimension(20, 22));

        javax.swing.GroupLayout ShadowUtama3Layout = new javax.swing.GroupLayout(ShadowUtama3);
        ShadowUtama3.setLayout(ShadowUtama3Layout);
        ShadowUtama3Layout.setHorizontalGroup(
            ShadowUtama3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ShadowUtama3Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(ShadowUtama3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ShadowUtama3Layout.createSequentialGroup()
                        .addComponent(jLabel19)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(ShadowUtama3Layout.createSequentialGroup()
                        .addGroup(ShadowUtama3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_KategoriEdit, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txt_HargaEdit, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(ShadowUtama3Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 720, Short.MAX_VALUE)
                                .addComponent(btnSimpanEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnKembaliE, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txt_JenisEdit, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 83, Short.MAX_VALUE))))
        );
        ShadowUtama3Layout.setVerticalGroup(
            ShadowUtama3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ShadowUtama3Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(ShadowUtama3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnKembaliE, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
                    .addComponent(btnSimpanEdit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_JenisEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_KategoriEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_HargaEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(730, Short.MAX_VALUE))
        );

        panelEdit.add(ShadowUtama3, "card2");

        panelAdd.add(panelEdit, "card2");

        panelMain.add(panelAdd, "card2");

        panelRiwayat.setLayout(new java.awt.CardLayout());

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        jLabel7.setText("Riwayat Setoran");

        btnKembaliR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icon_batal.png"))); // NOI18N
        btnKembaliR.setText("Kembali");
        btnKembaliR.setFillClick(new java.awt.Color(200, 125, 0));
        btnKembaliR.setFillOriginal(new java.awt.Color(243, 156, 18));
        btnKembaliR.setFillOver(new java.awt.Color(230, 145, 10));
        btnKembaliR.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnKembaliR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKembaliRActionPerformed(evt);
            }
        });

        table2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(table2);

        ShadowSearch1.setBackground(new java.awt.Color(249, 251, 255));
        ShadowSearch1.setPreferredSize(new java.awt.Dimension(259, 43));

        jLabel9.setBackground(new java.awt.Color(204, 204, 204));
        jLabel9.setForeground(new java.awt.Color(204, 204, 204));
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icon_search.png"))); // NOI18N
        jLabel9.setText("Search");

        javax.swing.GroupLayout ShadowSearch1Layout = new javax.swing.GroupLayout(ShadowSearch1);
        ShadowSearch1.setLayout(ShadowSearch1Layout);
        ShadowSearch1Layout.setHorizontalGroup(
            ShadowSearch1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ShadowSearch1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel9)
                .addContainerGap(180, Short.MAX_VALUE))
        );
        ShadowSearch1Layout.setVerticalGroup(
            ShadowSearch1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ShadowSearch1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        btnFirstPage.setText("First Page");
        btnFirstPage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFirstPageActionPerformed(evt);
            }
        });

        btnPrevious.setText("<");
        btnPrevious.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPreviousActionPerformed(evt);
            }
        });

        cbxPage.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnNext.setText(">");
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });

        btnLastPage.setText("Last Page");
        btnLastPage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLastPageActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ShadowUtama2Layout = new javax.swing.GroupLayout(ShadowUtama2);
        ShadowUtama2.setLayout(ShadowUtama2Layout);
        ShadowUtama2Layout.setHorizontalGroup(
            ShadowUtama2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ShadowUtama2Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(ShadowUtama2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(ShadowUtama2Layout.createSequentialGroup()
                        .addComponent(btnFirstPage)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPrevious)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbxPage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnNext)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnLastPage))
                    .addGroup(ShadowUtama2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane2)
                        .addGroup(ShadowUtama2Layout.createSequentialGroup()
                            .addComponent(jLabel7)
                            .addGap(603, 603, 603)
                            .addComponent(ShadowSearch1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnKembaliR, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 32, Short.MAX_VALUE))
        );
        ShadowUtama2Layout.setVerticalGroup(
            ShadowUtama2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ShadowUtama2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(ShadowUtama2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnKembaliR, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ShadowSearch1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 806, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(ShadowUtama2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(ShadowUtama2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnPrevious, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnNext, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnLastPage, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnFirstPage, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(cbxPage, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        panelRiwayat.add(ShadowUtama2, "card2");

        panelMain.add(panelRiwayat, "card2");

        add(panelMain, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void btnSimpanHargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanHargaActionPerformed
        try {
            String jenis = txt_JenisAdd.getText();
            String kategori = txt_KategoriAdd.getText();
            String harga = txt_HargaAdd.getText();
            int price = Integer.parseInt(harga);
            String sql = "INSERT INTO sampah (jenis_sampah, kategori_sampah, harga_sampah, tanggal) "
                    + "VALUES (?, ?, ?, CURRENT_DATE)";
            PreparedStatement pst = conn.prepareStatement(sql);
            pst.setString(1, jenis);
            pst.setString(2, kategori);
            pst.setDouble(3, price);
            pst.executeUpdate();

            JOptionPane.showMessageDialog(this, "Data berhasil disimpan.", "Sukses", JOptionPane.INFORMATION_MESSAGE);
            clearPanelAdd();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Gagal menyimpan data.", "Error", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_btnSimpanHargaActionPerformed

    private void btnKembaliTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKembaliTActionPerformed
        showPanel();
    }//GEN-LAST:event_btnKembaliTActionPerformed

    private void txt_NamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_NamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_NamaActionPerformed

    private void txt_BeratActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_BeratActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_BeratActionPerformed

    private void btn_SetorSampahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SetorSampahActionPerformed
        String kodeNasabah = txt_Kode.getText().trim();
        String nama = txt_Nama.getText().trim();
        String jenis = cbxJenis.getSelectedItem() != null ? cbxJenis.getSelectedItem().toString() : "";
        String kategori = cbxKategori.getSelectedItem() != null ? cbxKategori.getSelectedItem().toString() : "";
        String beratText = txt_Berat.getText().trim();

// Validasi input kosong
        if (kodeNasabah.isEmpty() || nama.isEmpty() || jenis.isEmpty() || kategori.isEmpty() || beratText.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Semua field harus diisi!", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }

// Validasi berat harus angka
        int berat;
        try {
            berat = Integer.parseInt(beratText);
            if (berat <= 0) {
                JOptionPane.showMessageDialog(null, "Berat harus lebih dari 0!", "Peringatan", JOptionPane.WARNING_MESSAGE);
                return;
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Berat harus berupa angka!", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }

        try {
            // Ambil ID Sampah dan harga
            String querySampah = "SELECT id_sampah, harga_sampah FROM sampah WHERE jenis_sampah=? AND kategori_sampah=?";
            PreparedStatement pstSampah = conn.prepareStatement(querySampah);
            pstSampah.setString(1, jenis);
            pstSampah.setString(2, kategori);
            ResultSet rsSampah = pstSampah.executeQuery();

            if (!rsSampah.next()) {
                JOptionPane.showMessageDialog(null, "Jenis dan kategori sampah tidak ditemukan di database!", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            int idSampah = rsSampah.getInt("id_sampah");
            int hargaPerKilo = rsSampah.getInt("harga_sampah");
            int hargaTotal = berat * hargaPerKilo;

            rsSampah.close();
            pstSampah.close();

            // Ambil ID Nasabah
            String queryNasabah = "SELECT id_nasabah FROM manajemen_nasabah WHERE kode_nasabah=?";
            PreparedStatement pstNasabah = conn.prepareStatement(queryNasabah);
            pstNasabah.setString(1, kodeNasabah);
            ResultSet rsNasabah = pstNasabah.executeQuery();

            if (!rsNasabah.next()) {
                JOptionPane.showMessageDialog(null, "Kode nasabah tidak ditemukan di database!", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            int idNasabah = rsNasabah.getInt("id_nasabah");

            rsNasabah.close();
            pstNasabah.close();

            // Insert data ke setor_sampah
            String insertQuery = "INSERT INTO setor_sampah (berat_sampah, harga, tanggal, id_sampah, id_nasabah) VALUES (?, ?, CURRENT_DATE, ?, ?)";
            PreparedStatement pstInsert = conn.prepareStatement(insertQuery);
            pstInsert.setInt(1, berat);
            pstInsert.setInt(2, hargaTotal);
            pstInsert.setInt(3, idSampah);
            pstInsert.setInt(4, idNasabah);

            int inserted = pstInsert.executeUpdate();
            pstInsert.close();

            if (inserted > 0) {
                JOptionPane.showMessageDialog(null, "Data berhasil disimpan!", "Sukses", JOptionPane.INFORMATION_MESSAGE);
                // opsional: kosongkan inputan setelah simpan
                txt_Kode.setText("");
                txt_Nama.setText("");
                txt_Berat.setText("");
                cbxJenis.setSelectedIndex(0);
                cbxKategori.setSelectedIndex(0);
            } else {
                JOptionPane.showMessageDialog(null, "Gagal menyimpan data!", "Error", JOptionPane.ERROR_MESSAGE);
            }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Terjadi kesalahan saat menyimpan data:\n" + e.getMessage(), "SQL Error", JOptionPane.ERROR_MESSAGE);
        }


    }//GEN-LAST:event_btn_SetorSampahActionPerformed

    private void btnTambahHargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahHargaActionPerformed
        panelMain.removeAll();
        panelMain.add(panelAdd);
        panelMain.repaint();
        panelMain.revalidate();
    }//GEN-LAST:event_btnTambahHargaActionPerformed

    private void btnBatalHargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalHargaActionPerformed
        showPanel();
    }//GEN-LAST:event_btnBatalHargaActionPerformed

    private void btnRiwayatSetorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRiwayatSetorActionPerformed
        panelMain.removeAll();
        panelMain.add(panelRiwayat);
        panelMain.repaint();
        panelMain.revalidate();
    }//GEN-LAST:event_btnRiwayatSetorActionPerformed

    private void btnKembaliRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKembaliRActionPerformed
        showPanel();
    }//GEN-LAST:event_btnKembaliRActionPerformed

    private void btnFirstPageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFirstPageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnFirstPageActionPerformed

    private void btnPreviousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPreviousActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPreviousActionPerformed

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNextActionPerformed

    private void btnLastPageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLastPageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLastPageActionPerformed

    private void txt_KodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_KodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_KodeActionPerformed

    private void txt_KodeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_KodeKeyPressed

    }//GEN-LAST:event_txt_KodeKeyPressed

    private void tblSampahMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblSampahMouseClicked
        int selectedRow = tblSampah.getSelectedRow(); // Mendapatkan indeks baris yang diklik
        if (selectedRow != -1) { // Pastikan ada baris yang dipilih
            // Atur tombol (disable tambah, enable edit dan hapus)
            btnTambahHarga.setEnabled(false);
            btnHapusHarga.setEnabled(true);
            btnEditHarga.setEnabled(true);
        }
    }//GEN-LAST:event_tblSampahMouseClicked

    private void btnHapusHargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusHargaActionPerformed
        int selectedRow = tblSampah.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(null, "Pilih data yang ingin dihapus!");
            return;
        }

        // Ambil kode produk dari tabel
        String dataSampah = (String) tblSampah.getValueAt(selectedRow, 0);

        // Konfirmasi penghapusan
        int confirm = JOptionPane.showConfirmDialog(null,
                "Apakah Anda yakin ingin menghapus harga sampah: " + dataSampah + "?",
                "Konfirmasi Hapus",
                JOptionPane.YES_NO_OPTION);

        if (confirm == JOptionPane.YES_OPTION) {
            // Hapus data terkait terlebih dahulu dari tabel lain
            String deleteHargaSampah = "DELETE FROM sampah WHERE kategori_sampah = ?";
            try (PreparedStatement pstmtDeleteFromPembelian = conn.prepareStatement(deleteHargaSampah)) {
                pstmtDeleteFromPembelian.setString(1, dataSampah);
                pstmtDeleteFromPembelian.executeUpdate();
            } catch (SQLException e) {
                e.printStackTrace();
                JOptionPane.showMessageDialog(null, "Error saat menghapus data harga sampah: " + e.getMessage());
                return;
            }

            // Sekarang hapus data dari tabel harga sampah
            String query = "DELETE FROM sampah WHERE kategori_sampah = ?";

            try (PreparedStatement pstmt = conn.prepareStatement(query)) {
                pstmt.setString(1, dataSampah);
                int rowsDeleted = pstmt.executeUpdate();

                if (rowsDeleted > 0) {
                    JOptionPane.showMessageDialog(null, "Data berhasil dihapus!");
                    loadTabelSampah(); // Refresh tabel
                } else {
                    JOptionPane.showMessageDialog(null, "Data tidak ditemukan!");
                }

            } catch (SQLException e) {
                e.printStackTrace();
                JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());
            }
        }
    }//GEN-LAST:event_btnHapusHargaActionPerformed

    private void btnEditHargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditHargaActionPerformed
        int selectedRow = tblSampah.getSelectedRow();
        if (selectedRow != -1) {
            setPanelEditFormData(selectedRow);
        }
        panelMain.removeAll();
        panelMain.add(panelEdit);
        panelMain.repaint();
        panelMain.revalidate();

    }//GEN-LAST:event_btnEditHargaActionPerformed

    private void btnSimpanEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanEditActionPerformed
        int selectedRow = tblSampah.getSelectedRow(); // Mendapatkan indeks baris yang diklik
        if (selectedRow >= 0) { // Pastikan ada baris yang dipilih
            // Ambil nilai dari baris yang dipilih dan masukkan ke text field
            setPanelEditFormData(selectedRow);
        }

        String jenis = txt_JenisEdit.getText();
        String kategori = txt_KategoriEdit.getText();
        String harga = txt_HargaEdit.getText();
        if (jenis.isEmpty() || kategori.isEmpty() || harga.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Harap lengkapi semua data!", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if (selectedIdSampah == -1) {
            JOptionPane.showMessageDialog(this, "ID sampah tidak ditemukan!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        try {
            String query = "UPDATE sampah SET jenis_sampah = ?, kategori_sampah = ?, harga_sampah = ? WHERE id_sampah = ?";
            PreparedStatement pst = conn.prepareStatement(query);

            pst.setString(1, jenis);
            pst.setString(2, kategori);
            pst.setDouble(3, Double.parseDouble(harga));
            pst.setInt(4, selectedIdSampah);
            // Eksekusi update
            int rowsUpdated = pst.executeUpdate();
            pst.close();

            if (rowsUpdated > 0) {
                JOptionPane.showMessageDialog(this, "Data berhasil diperbarui!", "Informasi", JOptionPane.INFORMATION_MESSAGE);
                clearPanelEdit();     // Bersihkan form
            } else {
                JOptionPane.showMessageDialog(this, "Gagal memperbarui data!", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Data harga harus berupa angka!", "Peringatan", JOptionPane.WARNING_MESSAGE);
        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnSimpanEditActionPerformed

    private void btnKembaliEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKembaliEActionPerformed
        showPanel();
    }//GEN-LAST:event_btnKembaliEActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private component.ShadowPanel ShadowSearch1;
    private component.ShadowPanel ShadowUtama;
    private component.ShadowPanel ShadowUtama1;
    private component.ShadowPanel ShadowUtama2;
    private component.ShadowPanel ShadowUtama3;
    private component.Jbutton btnBatalHarga;
    private component.Jbutton btnEditHarga;
    private javax.swing.JButton btnFirstPage;
    private component.Jbutton btnHapusHarga;
    private component.Jbutton btnKembaliE;
    private component.Jbutton btnKembaliR;
    private component.Jbutton btnKembaliT;
    private javax.swing.JButton btnLastPage;
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnPrevious;
    private component.Jbutton btnRiwayatSetor;
    private component.Jbutton btnSimpanEdit;
    private component.Jbutton btnSimpanHarga;
    private component.Jbutton btnTambahHarga;
    private component.Jbutton btn_SetorSampah;
    private javax.swing.JComboBox<String> cbxJenis;
    private javax.swing.JComboBox<String> cbxKategori;
    private javax.swing.JComboBox<String> cbxPage;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JPanel panelAdd;
    private javax.swing.JPanel panelEdit;
    private javax.swing.JPanel panelMain;
    private javax.swing.JPanel panelRiwayat;
    private javax.swing.JPanel panelView;
    private component.ShadowPanel shadowPanel1;
    private component.ShadowPanel shadowPanel2;
    private component.ShadowPanel shadowPanel3;
    private component.Table table2;
    private component.Table tblSampah;
    private javax.swing.JTextField txt_Berat;
    private javax.swing.JTextField txt_HargaAdd;
    private javax.swing.JTextField txt_HargaEdit;
    private javax.swing.JTextField txt_JenisAdd;
    private javax.swing.JTextField txt_JenisEdit;
    private javax.swing.JTextField txt_KategoriAdd;
    private javax.swing.JTextField txt_KategoriEdit;
    private javax.swing.JTextField txt_Kode;
    private javax.swing.JTextField txt_Nama;
    // End of variables declaration//GEN-END:variables
}
